KS-2-5 Solution for task 5 of lesson 2
Gadji1981/KotlinSprint pull request #11
Opened 2023-09-07 19:10 UTC by Gadji1981

2023-09-07 20:37 UTC, ievetrov requested changes

2023-09-07 20:37 UTC, ievetrov commented on src/main/kotlin/lesson_2/lesson_2_task_5.kt
> +    val balance: Double = deposit * Math.pow(1 + percentPerYear / 100, years.toDouble())
предлагаю использовать котлиновский экстеншен. он имеет немного другой синтаксис и не требует дополнительного обращения к Math

<img width="578" alt="image" src="https://github.com/Gadji1981/KotlinSprint/assets/34489023/7fe38ddb-d982-4dba-8481-791c6c4517a4">

2023-09-08 05:47 UTC, Gadji1981 commented on src/main/kotlin/lesson_2/lesson_2_task_5.kt
> +    val balance: Double = deposit * Math.pow(1 + percentPerYear / 100, years.toDouble())
но это вроде через функцию, а с функциями у меня пока туговато, есть масса вопросов и недопониманий(((

2023-09-11 21:19 UTC, ievetrov approved these changes
ага, отлично) ну на то и сложная задачка, чтобы не было очень скучно)

2023-09-14 18:06 UTC, merged