KS-4-2 Solution for task 2 of lesson 4 updated
Gadji1981/KotlinSprint pull request #18
Opened 2023-09-09 07:13 UTC by Gadji1981

2023-09-09 10:16 UTC, ievetrov requested changes

2023-09-09 10:16 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    //Вариант, если нужно с присвоением переменным:
а какой вариант мне проверять?)
(его все равно нужно доработать)

2023-09-09 10:16 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    println("Груз с весом 42 кг и объемом 120 л соответствует категории 'Average': ${42 in averageWeightRange && 120 < averageVolumeRange}")
значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)
не лучшая практика. добавь, пожалуйста, переменные)

2023-09-09 10:16 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    println("Груз с весом 42 кг и объемом 120 л соответствует категории 'Average': ${42 in averageWeightRange && 120 < averageVolumeRange}")
предлагаю еще создать константы для значений, с которым сравниваем входные данные

2023-09-09 10:16 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    println("Груз с весом 20 кг и объемом 80 л соответствует категории 'Average': ${20 in averageWeightRange && 80 < averageVolumeRange}")
Строки слишком длинные (>120 символов), глазу труднее в них ориентироваться. Часто в компаниях вводят правила форматирования, а также специальные утилиты, которые следят за соблюдением правил.

Вот например такая утилита Detekt для Kotlin запрещает по умолчанию строки длиннее 120 символов: https://detekt.dev/docs/rules/formatting/#maximumlinelength.
Давай добавим перенос или вынесем в переменную условие

2023-09-09 19:19 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    println("Груз с весом 42 кг и объемом 120 л соответствует категории 'Average': ${42 in averageWeightRange && 120 < averageVolumeRange}")
не выполнено(

2023-09-09 19:20 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    println("Груз с весом 20 кг и объемом 80 л соответствует категории 'Average': ${20 in averageWeightRange && 80 < averageVolumeRange}")
переносов тоже нет

2023-09-09 19:20 UTC, ievetrov requested changes
нет изменений по предыдущим комментариям

2023-09-09 19:24 UTC, Gadji1981 commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    println("Груз с весом 20 кг и объемом 80 л соответствует категории 'Average': ${20 in averageWeightRange && 80 < averageVolumeRange}")
что то поторопился((( исправил, переслал

2023-09-09 19:28 UTC, Gadji1981 commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +    println("Груз с весом 42 кг и объемом 120 л соответствует категории 'Average': ${42 in averageWeightRange && 120 < averageVolumeRange}")
блин! и это не заметил(((( исправляю((((

2023-09-11 10:28 UTC, ievetrov requested changes

2023-09-11 10:28 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_2.kt
> +                "${20 in AVERAGE_WEIGHT_MIN..AVERAGE_WEIGHT_MAX && 80 < AVERAGE_VOLUME_MAX}"
в целом все прекрасно, даже переменные объявлены для динамических весов) только почему-то эти переменные не замелили "магические числа" в коде)

2023-09-11 21:25 UTC, ievetrov approved these changes
прекрасно!

2023-09-14 18:08 UTC, merged