KS-4-3 Solution for task 3 of lesson 4
Gadji1981/KotlinSprint pull request #19
Opened 2023-09-09 07:58 UTC by Gadji1981

2023-09-09 10:19 UTC, ievetrov requested changes

2023-09-09 10:19 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    val weatherToday = true
Лучше использовать более релевантное название. В данном случае для Boolean переменной, которая является своеобразным "флагом" состояния. И для них рекомендуемая конструкция такая: isSunny / isAwningOpen

относится ко всем Boolean переменным

2023-09-09 10:19 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    val favorableConditions = weatherToday == true && tentOpen == true && airHumid == 20 && curentSeason == "не зима"
Согласно условию следует проинициализировать значения с которыми сравниваются критерии) их, кстати, стоит вынести в константы, так как они постоянные и не планируются изменяться.

2023-09-09 10:46 UTC, Gadji1981 commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    val favorableConditions = weatherToday == true && tentOpen == true && airHumid == 20 && curentSeason == "не зима"
вот этот момент упустил... правильно ли понимаю, что, для начала нужно cons val переменные, в уже в теле типа продублировать их в теле программы и уже потом проверять на условия?

2023-09-10 07:32 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +const val CURENT_SEASON = "не зима"
в значениях для сравнения храним только действительные значения. отрицание давай реализуем в самом условии

2023-09-10 07:32 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +    val favorableConditions = weatherToday == true && tentOpen == true && airHumid == 20 && curentSeason == "не зима"
да. константы - захардкоженные условия.
простые переменные инициализируются данными, которые приходят извне (например, из базы)

2023-09-10 14:32 UTC, Gadji1981 commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +const val CURENT_SEASON = "не зима"
вот тут немного запутался. можно поподробнее?(((

2023-09-11 16:11 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_3.kt
> +const val CURENT_SEASON = "не зима"
имеется в виду инициализируем исходными значениями (зима)
а в условии уже применяем символ отрицания `!`

2023-09-12 07:21 UTC, ievetrov approved these changes
красота, все ок!

2023-09-14 18:08 UTC, merged