KS-4-4 Solution for task 4 of lesson 4
Gadji1981/KotlinSprint pull request #20
Opened 2023-09-09 08:37 UTC by Gadji1981

2023-09-09 10:24 UTC, ievetrov requested changes

2023-09-09 10:24 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    val armsTraining = day in 0..10 step 2
а есть день станет 11 и далее?)

нужен немного другой подход. правильнее сделать программу универсальной, чтобы обрабатывался вообще любой по счету день. 

подход с вычислением четности переменной верный, как можно его пересмотреть и доработать?)

2023-09-09 12:45 UTC, Gadji1981 commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    val armsTraining = day in 0..10 step 2
вроде все замечания учел)

2023-09-10 09:35 UTC, ievetrov requested changes

2023-09-10 09:35 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    val armsTraining = isDayEven == false
отлично, можно еще сократить.
чтобы не сравнивать переменную с false и true, ведь она и так несет в себе какой-то Boolean.
ее сразу и присваивать. напрямую или с отрицанием

2023-09-10 13:40 UTC, Gadji1981 commented on src/main/kotlin/lesson_4/lesson_4_task_4.kt
> +    val armsTraining = isDayEven == false
исправил) сама идея даже подчеркнула с подсказкой

2023-09-11 10:29 UTC, ievetrov approved these changes
великолепно! все ок

2023-09-14 18:09 UTC, merged