KS-4-5 Solution for task 5 of lesson 4
Gadji1981/KotlinSprint pull request #21
Opened 2023-09-09 10:14 UTC by Gadji1981

2023-09-09 10:41 UTC, ievetrov requested changes

2023-09-09 10:41 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val shipDamage = readln() == "да"
Рекомендуется Boolean переменные называть, "отвечая на вопрос" да/нет.
Например, hasDamage, isDamaged

2023-09-09 10:41 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val shipDamage = readln() == "да"
также по ТЗ следует инициализировать сразу Boolean переменной (вводить true false)
и мы можем делать приведение типа по аналогии с toInt()

2023-09-09 10:41 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val sailingCondition = (shipDamage == false && crewNum in 55..70 && provisionBoxes > 50 && weather == true)
Значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)

корректнее вынести их в константы, чтобы было нагляднее и снизить риск ошибки

2023-09-09 19:14 UTC, ievetrov requested changes

2023-09-09 19:14 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +val CREW_NUMBER = 55..70
пропущено const

2023-09-09 19:14 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val isShipDamage = readln() == "да"
все таки не выполнено мое предложение)
тут конкретно надо с консоли считывать true или false
а затем приводить строку в Boolean типу

2023-09-09 19:14 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val isWeatherFavorable = readln() == "да"
и тут

2023-09-09 19:19 UTC, Gadji1981 commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val isShipDamage = readln() == "да"
ой... это забыл(((
хотел бы уточнить... переводить в boolean это так?
val isShipDamage = readln().toBoolean

2023-09-09 19:20 UTC, Gadji1981 commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +val CREW_NUMBER = 55..70
а вот тут не то что пропустил, идея выдавала ошибку и сама внесла такое изменение. писало что типа нельзя в const val  указывать переменные с диапазонами

2023-09-11 10:30 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val isShipDamage = readln() == "да"
да) сработало же) но надо доработать чуть

2023-09-11 10:32 UTC, ievetrov requested changes

2023-09-11 10:32 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val isShipDamage = readln().toBoolean() == true
с консоли мы сначала считываем строку true (например), затем приводим ее к типу Boolean. и на этом все, это значение и сохраняется в переменную isShipDamage. То есть не нужно дополнительно сравнивать через `==`. там и так уже сохраниться нужное булево значение.

2023-09-11 10:32 UTC, ievetrov commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val isWeatherFavorable = readln().toBoolean() == true
как и тут

2023-09-11 14:29 UTC, Gadji1981 commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val isShipDamage = readln().toBoolean() == true
изменил)

2023-09-11 14:29 UTC, Gadji1981 commented on src/main/kotlin/lesson_4/lesson_4_task_5.kt
> +    val isWeatherFavorable = readln().toBoolean() == true
изменил)

2023-09-11 21:26 UTC, ievetrov approved these changes
да, верно)

2023-09-14 18:09 UTC, merged