KS-6-3 Solution for task 3 of lesson 6
Gadji1981/KotlinSprint pull request #29
Opened 2023-09-14 16:58 UTC by Gadji1981

2023-09-15 08:10 UTC, ievetrov requested changes

2023-09-15 08:10 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_3.kt
> +        when(seconds) {
when для единственного ветвления не совсем принято использовать, для таких целей достаточно классического if.

а еще окончание таймера можно вынести за пределы цикла без всяких условий

2023-09-16 05:20 UTC, ievetrov requested changes

2023-09-16 05:20 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_3.kt
> +        }
теперь все супер) только немного поехало форматирование, попробуй перед коммитами делать автоформатирование)

2023-09-16 12:16 UTC, Gadji1981 commented on src/main/kotlin/lesson_6/lesson_6_task_3.kt
> +        }
никак не возьму за правило красоту кода(((

2023-09-16 23:32 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task_3.kt
> +        }
это приходит с опытом, скоро начнешь сам обращать на это внимание)

2023-09-16 23:32 UTC, ievetrov approved these changes

2023-09-17 05:15 UTC, merged