KS-6-4 Solution for task 4 of lesson 6
Gadji1981/KotlinSprint pull request #30
Opened 2023-09-14 17:35 UTC by Gadji1981

2023-09-15 08:12 UTC, ievetrov requested changes

2023-09-15 08:12 UTC, ievetrov commented on src/main/kotlin/lesson_6/lesson_6_task4.kt
> +            println()
предлагаю теперь не занимать лишнюю строку для создания отступа, а использовать символ переноса строки

2023-09-16 05:06 UTC, Gadji1981 commented on src/main/kotlin/lesson_6/lesson_6_task4.kt
> +            println()
исправил... изначально так и делал, но почему то показалось это менее эстетичным(

2023-09-16 05:18 UTC, ievetrov approved these changes

2023-09-17 05:16 UTC, merged