KS-8-3 Solution for task 3 of lesson 8
Gadji1981/KotlinSprint pull request #39
Opened 2023-09-17 11:53 UTC by Gadji1981

2023-09-18 12:14 UTC, ievetrov requested changes

2023-09-18 12:14 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_3.kt
> +    if (ingredients.any { it.contains(userInput, ignoreCase = true) }) {
Еще аккуратнее будет выглядеть, если проверять наличие элемента ключевым словом `in`

2023-09-18 17:39 UTC, Gadji1981 commented on src/main/kotlin/lesson_8/lesson_8_task_3.kt
> +    if (ingredients.any { it.contains(userInput, ignoreCase = true) }) {
исправил) в принципе в ТЗ нет ни слова о игноре регистра))))

2023-09-19 05:58 UTC, ievetrov commented on src/main/kotlin/lesson_8/lesson_8_task_3.kt
> +    if (ingredients.any { it.contains(userInput, ignoreCase = true) }) {
игнорировать регистр можно проще, храня в массиве элементы в маленьком регистре, а на введенный пользователем ответ применять `lowercase()`)

2023-09-19 05:58 UTC, ievetrov approved these changes

2023-09-21 08:21 UTC, merged