KS-1-5 Solution for task 5 of lesson 1
Gadji1981/KotlinSprint pull request #5
Opened 2023-09-07 14:20 UTC by Gadji1981

2023-09-07 14:34 UTC, ievetrov requested changes
задача "со звездочкой")
нужно произвести вычисления секунд в часы и минуты с помощью арифметических операций, а потом вывести все в корректном формате (как в примере)

2023-09-08 05:42 UTC, ievetrov requested changes

2023-09-08 05:42 UTC, ievetrov commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    print(hoursNew)
все хорошо, только можно еще сократить код, оставив только один `print` и объединив форматирования часов, минут и секунд) например таким образом:
`println(String.format("%02d:%02d:%02d", hours, minutes, secondsRemain))`

2023-09-08 05:44 UTC, Gadji1981 commented on src/main/kotlin/lesson_1/lesson_1_task_5.kt
> +    print(hoursNew)
а вот это уже возьму на заметку, эстетичней и более читаемо)

2023-09-08 18:55 UTC, ievetrov approved these changes
прекрасно!

2023-09-14 18:04 UTC, merged