KS-10-5 Solution for task 5 of lesson 10
Gadji1981/KotlinSprint pull request #51
Opened 2023-09-25 18:51 UTC by Gadji1981

2023-09-26 10:22 UTC, ievetrov requested changes
Давай по порядку. во первых логика нарушена - если ввести два раза пароль менее 4 символов - далее он его пропускает.

не пытайся сделать все в одном цикле, депомпозируй задачи на небольшие. вот например начать можно так. в цикле регистрации вводить имя пользователя, пока он не введет корректные данные

<img width="465" alt="image" src="https://github.com/Gadji1981/KotlinSprint/assets/34489023/9b7126ba-b0bb-40cc-825b-c5d0a1641575">

2023-10-02 09:03 UTC, ievetrov requested changes

2023-10-02 09:03 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_5.kt
> +        loginInput = readLine() ?: ""
а почему в одном месте readln а тут другой метод?)

2023-10-02 09:03 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_5.kt
> +    val pass = StringBuilder()
а можешь теперь обойтись без создания билдера?) просто складывая новый символ с ранее созданной строкой

2023-10-02 09:03 UTC, ievetrov commented on src/main/kotlin/lesson_10/lesson_10_task_5.kt
> +        if (!checkLoginLength(newUserInput)) println("Имя пользователя менее четырех символов.")
отлично. 
альтернативно checkLoginLength можно доработать и переименовать так, чтобы внутри делать печать.
тогда не придется здесь прописывать условие

2023-10-02 10:05 UTC, Gadji1981 commented on src/main/kotlin/lesson_10/lesson_10_task_5.kt
> +        loginInput = readLine() ?: ""
виноват. была ошибка, которую не мог найти, обращался к исправлению ИИ. Причем и ИИ не исправил ничего кроме данного метода, искал на просторах интернета, а код так и скопипейстил....

2023-10-02 20:59 UTC, ievetrov approved these changes
отлично!

2023-10-03 05:37 UTC, merged