KS-11-1 Solution for task 1 of lesson 11
Gadji1981/KotlinSprint pull request #52
Opened 2023-10-02 17:04 UTC by Gadji1981

2023-10-03 08:37 UTC, ievetrov requested changes

2023-10-03 08:37 UTC, ievetrov commented on src/main/kotlin/lesson_11/User.kt
> +class User(val id: Int, val userName: String, val password: String, val userEmail: String)
В аннотации к уроку я упоминаю создавать классы в одном файле. Перемести плиз)

2023-10-03 17:22 UTC, Gadji1981 commented on src/main/kotlin/lesson_11/User.kt
> +class User(val id: Int, val userName: String, val password: String, val userEmail: String)
блин! даже кепсом написано, а слона то и не заметил(((

2023-10-04 09:49 UTC, ievetrov approved these changes

2023-10-09 14:57 UTC, merged