KS-13-5 Solution for task 5 of lesson 13
Gadji1981/KotlinSprint pull request #66
Opened 2023-10-18 18:02 UTC by Gadji1981

2023-10-19 11:15 UTC, ievetrov requested changes

2023-10-19 11:15 UTC, ievetrov commented on src/main/kotlin/lesson_13/lesson_13_task_5.kt
> +    val phoneNumber = readln().toLong()
а где код из предыдущей задачи?

2023-10-19 15:37 UTC, Gadji1981 commented on src/main/kotlin/lesson_13/lesson_13_task_5.kt
> +    val phoneNumber = readln().toLong()
виноват... неправильно понял условие задания. думал **без логики заполнения телефонной книги** это вообще голое тело...

2023-10-20 10:49 UTC, ievetrov requested changes

2023-10-20 10:49 UTC, ievetrov commented on src/main/kotlin/lesson_13/lesson_13_task_5.kt
> +    val phoneBook = mutableListOf<PhoneBook4>()
в функции main как раз логика заполнения и она не нужна) нужно оставить только `PhoneBook4` и сделать решение этой задачи в main)

2023-10-21 13:17 UTC, Gadji1981 commented on src/main/kotlin/lesson_13/lesson_13_task_5.kt
> +    val phoneBook = mutableListOf<PhoneBook4>()
аааа..... т.е. в main ничего кроме запроса на ввод номера телефона не оставлять? а класс так же оставить как есть?

2023-10-22 13:49 UTC, ievetrov commented on src/main/kotlin/lesson_13/lesson_13_task_5.kt
> +    val phoneBook = mutableListOf<PhoneBook4>()
да, теперь все правильно))

2023-10-22 13:49 UTC, ievetrov approved these changes

2023-10-22 15:09 UTC, merged